# needed to get a protobuf-compiler that supports Protobufs v3
dist: bionic

language: node_js
node_js:
  - 11.15.0

cache: yarn

addons:
  apt:
    update: true
    packages:
      - libprotobuf-dev

before_install:
  # Install protobuf
  # Ubuntu has 3.0 in the repositories
  - curl -OL https://github.com/google/protobuf/releases/download/v3.7.1/protoc-3.7.1-linux-x86_64.zip
  - sudo unzip -o protoc-3.7.1-linux-x86_64.zip -d /usr/local bin/protoc
  - sudo unzip -o protoc-3.7.1-linux-x86_64.zip -d /usr/local include/*
  - rm -f protoc-3.7.1-linux-x86_64.zip

script:
  - yarn lint
  - yarn test
