version: "3"

silent: true

tasks:
    default:
        deps:
            - build

    install:
        cmds:
            - pnpm i

    build:
        cmds:
            - task: install
            - task: format
            - task: lint

    clean:
        cmds:
            - rm -rf node_modules

    format:
        cmds:
            - ./node_modules/.bin/prettier "*.json" "src/*.js" --write > /dev/null

    lint:
        deps:
            - "lint:types"
            - "lint:format"
            - "lint:js"

    "lint:types":
        cmds:
            - ./node_modules/.bin/tsc

    "lint:format":
        cmds:
            - ./node_modules/.bin/prettier "*.json" "src/*.js" --check > /dev/null

    "lint:js":
        cmds:
            - ./node_modules/.bin/eslint --fix "src/*.js"

    test:
        deps:
            - "test:unit"

    "test:unit":
        deps:
            - "test:unit:node"

    "test:unit:node":
        cmds:
            - ./node_modules/.bin/mocha --inline-diffs -r @babel/register -r chai/register-expect.js "test/*.js" {{.CLI_ARGS}}
