version: "3"

silent: true

includes:
    tck-chai:
        taskfile: ../../packages/tck-chai/Taskfile.yml
        dir: ../../packages/tck-chai

tasks:
    default:
        deps:
            - build

    install:
        cmds:
            - pnpm i > /dev/null

    build:
        cmds:
            - task: install
            - task: format
            - ./node_modules/.bin/tsup src/**.ts > /dev/null

    run:
        cmds:
            - ./node_modules/.bin/ts-node src/index

    clean:
        cmds:
            - rm -rf node_modules

    format:
        cmds:
            - ./node_modules/.bin/prettier "*.json" "src/*.ts" --write > /dev/null

    lint:
        deps:
            - "lint:types"
            - "lint:format"

    "lint:types":
        cmds:
            - ./node_modules/.bin/tsc

    "lint:format":
        cmds:
            - ./node_modules/.bin/prettier "*.json" "src/*.ts" --check > /dev/null

    test:
        deps:
            - "test:unit"

    "test:unit":
        deps:
            - "test:unit:node"

    "test:unit:node":
        cmds:
            - ./node_modules/.bin/ts-mocha --inline-diffs -r @babel/register -r chai/register-expect.js "test/tck.ts" {{.CLI_ARGS}}

    update:
        cmds:
            - task: tck-chai:build
            - task: build
