name: Hedera Services Main

on:
    push:
        branches:
            - integration-test-workflow

env:
    RELAY_IMAGE_TAG: main
    NETWORK_NODE_IMAGE_TAG: 0.31.0
    HAVEGED_IMAGE_TAG: 0.31.0
    MIRROR_IMAGE_TAG: 0.67.0-rc1

jobs:
    test:
        runs-on: ubuntu-latest
        timeout-minutes: 35
        strategy:
            fail-fast: false

        permissions:
            contents: write

        steps:
            - name: Cache pnpm modules
              uses: actions/cache@v2
              env:
                  cache-name: cache-pnpm-modules
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/package.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-

            - name: Use Node.js [16.x]
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install Task
              uses: arduino/setup-task@v1
              with:
                  version: 3.7.0

            - uses: pnpm/action-setup@v2.0.1
              with:
                  version: 7.6.0

            - name: Install Docker Compose
              run: |
                  sudo curl -SL -o /usr/local/bin/docker-compose https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
                  sudo chmod +x /usr/local/bin/docker-compose

            - name: Start the local node
              run: npx hedera start -d --network local

            - name: Fetch Hedera SDK
              uses: actions/checkout@v2
              with:
                  submodules: recursive
                  path: hedera-sdk-js

            - name: Run Hedera SDK Tests
              env:
                  OPERATOR_KEY: "302e020100300506032b65700422042091132178e72057a1d7528025956fe39b0b847f200ab59b2fdd367017f3087137"
                  OPERATOR_ID: "0.0.2"
                  HEDERA_NETWORK: "localhost"
              run: |
                  task build
                  task test:integration:node

            - name: Stop the local node
              run: npx hedera stop
